services:

  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres_data:
